# Generated by Django 4.1.3 on 2022-12-23 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearPlatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('store_city', models.CharField(max_length=100)),
                ('store_state', models.CharField(max_length=100)),
                ('store_zip', models.CharField(max_length=100)),
                ('store_country', models.CharField(max_length=100)),
                ('store_phone', models.CharField(max_length=100)),
                ('store_website', models.URLField(max_length=100)),
                ('store_description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='gear',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
