# Generated by Django 4.1.3 on 2022-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gearplatform_gear_created_alter_gear_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='store',
            field=models.ManyToManyField(to='gear.gearplatform'),
        ),
    ]
