# Generated by Django 4.1.3 on 2022-12-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_remove_gear_store_gear_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gear.gearplatform'),
        ),
    ]
